version: "3.4"

services:
  mysql:
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /d/docker/data/mysql:/var/lib/mysql

  redis:
    environment:
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /d/docker/data/redis:/data

  rabbitmq:
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  mssql:
    environment:
      - TZ=Asia/Shanghai
      - SA_PASSWORD=${SQL_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - /d/docker/data/mssql:/var/opt/mssql
